### ISSUE TITLE
Can not use the `redirect` auth method.

### ISSUE THREAD

**Issue by dbinetti** [seawatts/ember-simple-auth-auth0#27]
When I put `redirect: true` on the `auth` params, I can't authenticate.  The URL is not being parsed, and I just sit on there with the `access_token` in the URL.  (Related, I can't impersonate for the same reason.)  Might be misconfiguring something.

**Comment by seawatts** [comment]
Hmm yeah I was wondering about that. This is due to this library not handling the redirect params correctly. I'll look into a better way to do this.

**Comment by drewnichols** [comment]
I should add that if you specify a callback url in the authenticate options ie: `redirectUrl: 'http://localhost:4200/auth0callback'` auth0 redirects back to the provided url with just a code:

`http://localhost:4200/auth0callback?code=n0v92zYwCen0sRb7#`

**Comment by seawatts** [comment]
This should now be fixed in #18

**Comment by dbinetti** [comment]
So with Ember Simple Auth v1.2.0 and Ember Simple Auth Auth0 v 2.2.1 on Ember v 2.10.0 I still can't authenticate with `redirect:true`.  here are all my lock options:

```
    login () {
      var lockOptions = {
        allowedConnections: [
          'Default',
        ],
        autoclose: true,
        allowLogin: true,
        allowSignUp: false,
        rememberLastLogin: true,
        theme: {
          logo: 'https://s3-us-west-1.amazonaws.com/barberscore/static/app/bhs_logo.png',
          primaryColor: '#337ab7'
        },
        languageDictionary: {
          title: "Barberscore"
        },
        auth: {
          redirect: true,
          params: {
            scope: 'openid profile',
          }
        }
      };
      this.get('session').authenticate('authenticator:auth0-lock', lockOptions);
    },
```

**Comment by dbinetti** [comment]
Oh and it's the same thing-- the URL gets the access_token, but it is not being parsed.
